DELIMITER $$

CREATE PROCEDURE ShowAgentPerformance()
BEGIN
    SELECT a.AGENT_NAME,SUM(c.OUTSTANDING_AMT) FROM agents a INNER JOIN customer c ON a.AGENT_CODE = c.AGENT_CODE
    GROUP BY c.AGENT_CODE;
END$$

DELIMITER ;