CREATE TABLE `order_logs` ( 
    `ORD_AMOUNT` DECIMAL(10,0) NOT NULL ,  
    `ADVANCE_AMOUNT` DECIMAL(10,0) NOT NULL ,  
    `TIMESTAMP` TIMESTAMP NOT NULL ) 
ENGINE = InnoDB;

DELIMITER $$

CREATE TRIGGER `order_changed` AFTER UPDATE ON `orders` FOR EACH ROW
BEGIN
INSERT INTO order_logs(`ORD_AMOUNT`,`ADVANCE_AMOUNT`) VALUES (OLD.ORD_AMOUNT,OLD.ADVANCE_AMOUNT);
END$$

DELIMITER ;